# Generated by Django 5.0.7 on 2025-06-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.visitreason')),
            ],
        ),
        migrations.CreateModel(
            name='EventSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendee_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.visitreason')),
            ],
        ),
    ]
